const ErrorType = {
  General: {
    ERROR_NO_TOKEN: "GENERAL.ERROR_NO_TOKEN",
    ERROR_INVALID_TOKEN: "GENERAL.ERROR_INVALID_TOKEN",
    INTERNAL_SERVER_ERROR: "GENERAL.INTERNAL_SERVER_ERROR",
  },
  User: {
    ERROR_GETTING_USER: "USER.ERROR_GETTING_USER",
    ERROR_USER_NOT_FOUND: "USER.ERROR_USER_NOT_FOUND",
    ERROR_USER_INSERTING_RECORD: "USER.ERROR_USER_INSERTING_RECORD",
    ERROR_USER_INVALID_CREDENTIALS: "USER.ERROR_USER_INVALID_CREDENTIALS",
  },
}

export default ErrorType;